//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoP1Web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos_GrupoGimnasio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos_GrupoGimnasio()
        {
            this.Asistencia = new HashSet<Asistencia>();
        }
    
        public string Matricula { get; set; }
        public int idGimnasio { get; set; }
        public int idAlumnos_GrupoGimnasio { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual GrupoGimnasio GrupoGimnasio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
    }
}
