//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoP1Web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogocoord
    {
        public int clavecct { get; set; }
        public string nombre { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string lada { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
    }
}
