//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoP1Web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioGimnasio_Hora
    {
        public int idHorarioGimnasio_Horas { get; set; }
        public int IdHora { get; set; }
        public int IdHorario { get; set; }
        public string Dia { get; set; }
    
        public virtual Hora Hora { get; set; }
        public virtual HorarioGimnasio HorarioGimnasio { get; set; }
    }
}
