//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoP1Web2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaGimnasioEntities : DbContext
    {
        public SistemaGimnasioEntities()
            : base("name=SistemaGimnasioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Alumnos_GrupoGimnasio> Alumnos_GrupoGimnasio { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<catalogocoord> catalogocoord { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<GrupoGimnasio> GrupoGimnasio { get; set; }
        public virtual DbSet<Hora> Hora { get; set; }
        public virtual DbSet<HorarioGimnasio> HorarioGimnasio { get; set; }
        public virtual DbSet<HorarioGimnasio_Hora> HorarioGimnasio_Hora { get; set; }
        public virtual DbSet<Licenciatura> Licenciatura { get; set; }
        public virtual DbSet<MigrationHistory> MigrationHistory { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
    }
}
